### ISSUE TITLE
[install] Failed at the simplehttp2server@2.0.0 postinstall script.

### ISSUE THREAD

**Issue by Mathieu-R** [developit/preact-cli#116]
Hey, 

I'm unable to install `preact-cli` _(npm i -g preact-cli)_ and I've got this error in the terminal :

```
/usr/bin/simplehttp2server -> /usr/lib/node_modules/simplehttp2server/cli.js

> simplehttp2server@2.0.0 postinstall /usr/lib/node_modules/simplehttp2server
> node lib/install.js

fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/lib/node_modules/simplehttp2server/node_modules/array-unique/index.js'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/simplehttp2server/node_modules/micromatch/lib/utils.js:13:16)
    at Module._compile (module.js:569:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simplehttp2server@2.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the simplehttp2server@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-15T20_08_52_596Z-debug.log
```

The error seems to be in touch with the npm package `simplehttp2server`.
Thanks in advance for the help ! :smile:

**Comment by lukeed** [comment]
Any chance your npm is configured to need `sudo` for global access?

**Comment by Mathieu-R** [comment]
@lukeed  Well, yes indeed, I need to type `sudo npm i -g <package>` to install global package. Is that a problem ?

**Comment by lukeed** [comment]
Ah, okay. Then yeah, that's what you need to do.

It's not a `preact-cli` problem -- or even a problem, really --- it's just how you configured `npm` to operate.

**Comment by Mathieu-R** [comment]
Okay, thanks ! Didn't know about that. Thought that installing global package with sudo was a common or even the only practice.

**Comment by thangngoc89** [comment]
I usually use nvm to install and manage node version. No need for sudo to install global package. Pretty sure you can configure it by hand but why bother when we have nvm

**Comment by lukeed** [comment]
^^ Yup. I moved to `nvm` a few years ago & I've never had to change or second-guess anything since.

**Comment by bchociej** [comment]
Granted that it's not preact-cli's problem, but needing root to install globally is the correct situation for many distro-packaged node.js installs, so it should be supported.

**Comment by thangngoc89** [comment]
@bchociej It's supported. You just need to give it sudo permission.

**Comment by bchociej** [comment]
Ack, sorry. I ran it once with sudo and it didn't work:

```$ sudo npm i -g preact-cli
Password: 
/usr/bin/preact -> /usr/lib/node_modules/preact-cli/lib/index.js

> fsevents@1.1.2 install /usr/lib/node_modules/preact-cli/node_modules/fsevents
> node install


> simplehttp2server@2.0.0 postinstall /usr/lib/node_modules/preact-cli/node_modules/simplehttp2server
> node lib/install.js

fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/lib64/node_modules/preact-cli/node_modules/array-unique/index.js'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib64/node_modules/preact-cli/node_modules/micromatch/lib/utils.js:13:16)
    at Module._compile (module.js:569:30)
npm WARN /usr/lib64/node_modules/preact-cli is not a child of /usr/lib
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simplehttp2server@2.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the simplehttp2server@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above```

However, running it a second time worked fine. Sorry to bother prematurely!
