### ISSUE TITLE
Installation errors and warnings 

### ISSUE THREAD

**Issue by marvinhagemeister** [developit/preact-cli#26]
I'm having trouble installing preact-cli this morning. Tested on MacOS and inside a fresh linux vm and docker image:

```bash
$ npm install -g preact-cli
/usr/local/bin/preact -> /usr/local/lib/node_modules/preact-cli/lib/index.js

> fsevents@1.1.1 install /usr/local/lib/node_modules/preact-cli/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/preact-cli/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote

> simplehttp2server@1.0.0 postinstall /usr/local/lib/node_modules/preact-cli/node_modules/simplehttp2server
> node lib/install.js

  ⚠ The `/usr/local/lib/node_modules/preact-cli/node_modules/simplehttp2server/vendor/simplehttp2server` binary doesn't seem to work correctly
  ⚠ simplehttp2server pre-build test failed
  ℹ compiling from source
  ✖ Error: mkdir -p /usr/local/lib/node_modules/preact-cli/node_modules/simplehttp2server/vendor && sh crosscompile.sh && mv ./57924994-9b31-49b1-afa2-51924472b375_darwin_amd64 /usr/local/lib/node_modules/preact-cli/node_modules/simplehttp2server/vendor/simplehttp2server
Command failed: sh crosscompile.sh && mv ./57924994-9b31-49b1-afa2-51924472b375_darwin_amd64 /usr/local/lib/node_modules/preact-cli/node_modules/simplehttp2server/vendor/simplehttp2server
simplehttp2server.go:24:2: cannot find package "github.com/NYTimes/gziphandler" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/NYTimes/gziphandler (from $GOROOT)
	/Users/marvinhagemeister/go/src/github.com/NYTimes/gziphandler (from $GOPATH)
simplehttp2server.go:24:2: cannot find package "github.com/NYTimes/gziphandler" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/NYTimes/gziphandler (from $GOROOT)
	/Users/marvinhagemeister/go/src/github.com/NYTimes/gziphandler (from $GOPATH)
simplehttp2server.go:24:2: cannot find package "github.com/NYTimes/gziphandler" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/NYTimes/gziphandler (from $GOROOT)
	/Users/marvinhagemeister/go/src/github.com/NYTimes/gziphandler (from $GOPATH)
simplehttp2server.go:24:2: cannot find package "github.com/NYTimes/gziphandler" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/NYTimes/gziphandler (from $GOROOT)
	/Users/marvinhagemeister/go/src/github.com/NYTimes/gziphandler (from $GOPATH)
simplehttp2server.go:24:2: cannot find package "github.com/NYTimes/gziphandler" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/NYTimes/gziphandler (from $GOROOT)
	/Users/marvinhagemeister/go/src/github.com/NYTimes/gziphandler (from $GOPATH)

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
/usr/local/lib

# ... (long npm output here)

npm WARN preact-render-to-string@3.6.2 requires a peer of preact@* but none was installed.
```

The last error, that `preact` is not installed properly should be an easy fix. The issue with `simplehttp2server` seems a bit more involved.

**Comment by developit** [comment]
Both are warnings and the install should actually work. I'm not sure what we can do about the Go thing, that's just the output of the node wrapper we use to install simplehttp2server - it tries a bunch of methods and uses whatever works. 
The preact peer dep issue we can fix though.

**Comment by marvinhagemeister** [comment]
Seems like this is a duplicate of https://github.com/developit/preact-cli/issues/24

**Comment by developit** [comment]
Yup!  I was thinking of closing it once the peer dependency issue is fixed.

**Comment by redstrike** [comment]
I got this issue on Windows 10 too.
**It works after I upgraded to Go v1.8.3** from v1.8.0 😇

**Comment by thangngoc89** [comment]
@redstrike Hum.. I didn't install Go development environment on my machine, shouldn't it have a prebuilt binary?

**Comment by redstrike** [comment]
@thangngoc89 I'm using a Windows machine, so I just downloaded **go1.8.3.windows-amd64.msi** at [Downloads page](https://golang.org/dl/), then run it > Next > Next ... 😃 So easy, isn't it?

**Comment by thangngoc89** [comment]
@redstrike I mean it shouldn't be a requirement. Most node.js library have prebuilt version of the binary included. Maybe this is something to report back to the project's owner?

**Comment by marvinhagemeister** [comment]
@thangngoc89 It's still unresolved on their end. See https://github.com/GoogleChrome/simplehttp2server/issues/27

**Comment by rkostrzewski** [comment]
@marvinhagemeister closing this because apparently it works based on [this](https://github.com/1000ch/simplehttp2server/issues/2#issuecomment-306712796).
Feel free to reopen if it doesn't tough. 😄
