### ISSUE TITLE
Syntax error at run-webpack.js

### ISSUE THREAD

**Issue by nicohsieh** [developit/preact-cli#292]
I just installed preact-cli and got the error below when running any commands. Not sure if I missed anything?

```
/usr/local/lib/node_modules/preact-cli/lib/lib/webpack/run-webpack.js:52
	var _ref = _asyncToGenerator(function* (watch = false, env, onprogress) {
	                                              ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/preact-cli/lib/commands/build.js:19:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by thangngoc89** [comment]
@nicohsieh which node version you're runnig? We requires at least node 6

**Comment by reznord** [comment]
There was a bug in `check.js` which checks for the required node version.

I have fixed that issue and it will be working in the next version. 

@nicohsieh The minimum required node version is v6.

**Comment by nicohsieh** [comment]
Thanks for the quick reply!
