### ISSUE TITLE
npm i -g preact-cli =>   Error: Cannot find module 'config/donation-message.js'

### ISSUE THREAD

**Issue by rvion** [developit/preact-cli#342]
**Do you want to request a *feature* or report a *bug*?**

BUG 

**What is the current behavior?**

```sh 
npm i -g preact-cli

[...]
> preact@8.2.2 postinstall /usr/local/lib/node_modules/preact-cli/node_modules/preact
> node ./config/donation-message.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/preact-cli/node_modules/preact/config/donation-message.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

```

**Please mention other relevant information.**

- node -v v6.10.2
- npm -v 3.10.10 (bug also happens with latest yarn)
- osx

**Comment by lukeed** [comment]
This is actually a (new) issue with Preact itself: https://github.com/developit/preact/issues/834

**Comment by developit** [comment]
sorry
