### ISSUE TITLE
Supporting source-maps in development mode

### ISSUE THREAD

**Issue by thangngoc89** [developit/preact-cli#44]
Unless I did something wrong, I can tell that preact-cli doesn't provide source map for development. I'm seeing cryptic error like this: 

```
VM2163:37 Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('[object Object]') is not a valid name.
    at u (eval at <anonymous> (http://localhost:8080/bundle.js:830:1), <anonymous>:37:86)
    at m (eval at <anonymous> (http://localhost:8080/bundle.js:830:1), <anonymous>:70:471)
    at h (eval at <anonymous> (http://localhost:8080/bundle.js:830:1), <anonymous>:67:110)
    at k (eval at <anonymous> (http://localhost:8080/bundle.js:830:1), <anonymous>:149:113)
    at k (eval at <anonymous> (http://localhost:8080/bundle.js:830:1), <anonymous>:148:185)
    at x (eval at <anonymous> (http://localhost:8080/bundle.js:830:1), <anonymous>:128:419)
    at U (eval at <anonymous> (http://localhost:8080/bundle.js:830:1), <anonymous>:169:176)
    at m (eval at <anonymous> (http://localhost:8080/bundle.js:830:1), <anonymous>:70:349)
    at v (eval at <anonymous> (http://localhost:8080/bundle.js:830:1), <anonymous>:98:12)
    at m (eval at <anonymous> (http://localhost:8080/bundle.js:830:1), <anonymous>:76:228)
```

**Comment by developit** [comment]
I think you might have them turned off in DevTools.

Here's the line that should be enabling inline sourcemaps during development and external sourcemaps for production:
https://github.com/developit/preact-cli/blob/master/src/lib/webpack-config.js#L255-L256

**Comment by rkostrzewski** [comment]
BTW source maps are not generated for production build too ```preact build```.

**Comment by thangngoc89** [comment]
Ctrl + C and `npm start` fixed this. I'm not sure why I see this last time, but these stuff happens with Webpack

**Comment by developit** [comment]
This is funky. I wonder if it's an issue with `webpack-blocks`?  The `setDevTool` blocks [seems pretty simple](https://github.com/andywer/webpack-blocks/blob/master/packages/webpack-common/src/webpack.js#L101-L103), it just sets `config.devtool` to whatever value is passed.

**Comment by rkostrzewski** [comment]
@thangngoc89 I'll be closing this since you manged to resolve this. As for production bundle - #103
