### ISSUE TITLE
Test script exits with path error

### ISSUE THREAD

**Issue by elisechant** [developit/preact-cli#495]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behaviour?**
Test script exits with path error.

**If the current behaviour is a bug, please provide the steps to reproduce.**
Run `npm run test`

Output: 

 ```
$ NODE_ENV=test jest ./tests
 FAIL  src/tests/header.test.js
  ● Test suite failed to run

   Cannot find module './lib/lib/babel-config' (While processing preset: "/Users/elisechant/Sites/codeforaustralia/cese-snippet/node_modules/preact-cli/babel/index.js")

      at Function.Module._resolveFilename (module.js:538:15)
      at Function.Module._load (module.js:468:25)
      at Module.require (module.js:587:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (node_modules/preact-cli/babel/index.js:13:20)
      at Module._compile (module.js:643:30)
      at Object.Module._extensions..js (module.js:654:10)
      at Module.load (module.js:556:32)
      at tryModuleLoad (module.js:499:12)
      at Function.Module._load (module.js:491:3)
```

**What is the expected behaviour?**
Boilerplate header.test should pass.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version 8.9.4
- npm version 5.6.0
- Operating system OSX
- CLI version 2.1.2
- Browser n/a

Fix: 

Incorrect path reference is here:

node_modules/preact-cli/babel/index.js:13

fix is: 

```var babelConfigs = require("./lib/lib/babel-config").default;```

to

```var babelConfigs = require("./../lib/lib/babel-config").default;```

**Comment by developit** [comment]
Fixed by #496! Thanks @elisechant!!
