### ISSUE TITLE
2.1.3 build/watch not working

### ISSUE THREAD

**Issue by joacim88** [developit/preact-cli#498]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
When I run preact build or preact watch with 2.1.3 i get this error

`preact watch
module.js:538
    throw err;
    ^

Error: Cannot find module 'update-notifier'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\joagun\AppData\Roaming\npm\node_modules\preact-cli\lib\index.js:4:23)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)`

**If the current behaviour is a bug, please provide the steps to reproduce.**
preact watch 
preact build

**What is the expected behaviour?**

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version 8.9.1
- npm version 5.5.1
- Operating system Win 10
- CLI version 2.1.3
- Browser

**Comment by joacim88** [comment]
Hmm, never mind this.

I ran a npm i -g preact-cli again and it worked again.

**Comment by reznord** [comment]
Probably might be because of bad network connection.
