### ISSUE TITLE
Importing .json fails in next branch

### ISSUE THREAD

**Issue by prateekbh** [developit/preact-cli#613]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
`impost json from '../X.json'` fails with the message

```
Module parse failed: Unexpected token m in JSON at position 0 while parsing near 'module.exports = {"n...'
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token m in JSON at position 0 while parsing near 'module.exports = {"n...'
    at JSON.parse (<anonymous>)
    at parseJson (/Users/prateekbh/projects/preact-cli/packages/cli/node_modules/json-parse-better-errors/index.js:7:17)
    at JsonParser.parse (/Users/prateekbh/projects/preact-cli/packages/cli/node_modules/webpack/lib/JsonParser.js:16:16)
    at doBuild.err (/Users/prateekbh/projects/preact-cli/packages/cli/node_modules/webpack/lib/NormalModule.js:462:32)
    at runLoaders (/Users/prateekbh/projects/preact-cli/packages/cli/node_modules/webpack/lib/NormalModule.js:344:12)
    at /Users/prateekbh/projects/preact-cli/packages/cli/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/prateekbh/projects/preact-cli/packages/cli/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/Users/prateekbh/projects/preact-cli/packages/cli/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/prateekbh/projects/preact-cli/packages/cli/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at runSyncOrAsync (/Users/prateekbh/projects/preact-cli/packages/cli/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/prateekbh/projects/preact-cli/packages/cli/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at /Users/prateekbh/projects/preact-cli/packages/cli/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at process.nextTick (/Users/prateekbh/projects/preact-cli/packages/cli/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 @ ./components/menu/index.js 11:0-44 83:26-30
 @ ./components/app/index.js
 @ ./index.js
```

**If the current behaviour is a bug, please provide the steps to reproduce.**
1. Create a new project with next branch(`preact create default blah`)
2. Add `import packageDetails from '../package.json'` to index.js
3. Run `preact build` or `preact serve`.

**What is the expected behaviour?**
It should build.

**Solution**
Delete these lines: https://github.com/developit/preact-cli/blob/bc0c665f77841e755a913bcdf7a1434da2195221/src/lib/webpack/webpack-base-config.js#L189-L192

As webpack takes care of json files on its own now.

**Comment by prateekbh** [comment]
CC: @lukeed @ForsakenHarmony 

lemme know if this sounds good, i'll create the PR

**Comment by lukeed** [comment]
Sure, go for it! Not using `json-loader` locally either and it works fine. Project was archived by webpack team too.
