### ISSUE TITLE
Service worker does not registered in production Firebase Hosting

### ISSUE THREAD

**Issue by adrienshen** [developit/preact-cli#686]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behaviour?**
The sw.js is not registering in production. Please look at the dropbox screenshots
https://www.dropbox.com/s/l14n44w2ax7t6ws/Scrreenshot%202018-12-16%2023.44.16.png?dl=0
https://www.dropbox.com/s/jl95a6fdj22tlhm/Screenshot%202018-12-16%2023.48.02.png?dl=0

**If the current behaviour is a bug, please provide the steps to reproduce.**
I developed the app, then yarn build and deployed to Firebase Hosting. Shows error in registering `Uncaught (in promise) TypeError: Failed to fetch` which isn't too helpful.

**What is the expected behaviour?**
The service worker should be working without any further modification automatically.

**Please mention other relevant information.**
- Node version = v11.1.0
- npm version = 6.5.0
- Operating system = MacOS Sierra
- CLI version = Firebase 6.0.1
- Browser = Chrome 71

**Comment by prateekbh** [comment]
hi
can you post the network tab output to show which file is 404

**Comment by liamthorpeyoung** [comment]
This is what I'm getting in the network tab...

![Screen Shot 2019-03-11 at 17 00 54](https://user-images.githubusercontent.com/26540192/54142328-5a3af900-441f-11e9-8d2e-b165aa4fdbe6.png)

**Comment by SpaceHeroGuide** [comment]
Any solution for this? Chrome fails when registering the service worker:

```
Uncaught (in promise) TypeError: Failed to fetch
    at e.cacheWillUpdate (https://**.***.**/sw-esm.js:3:1331)
    at l.o (https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-precaching.prod.js:1:1695)
    at async Promise.all (index 1)
    at async l.install (https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-precaching.prod.js:1:1221)
```

I deployed the PWA to S3 and access it via cloudfront.

**Comment by mathshenry** [comment]
Was there a solution for this case? I'm facing the same issue. I can get Service Worker to be registered when running locally, but when hosting on Firebase Hosting, it won't register and no error shows up.
