### ISSUE TITLE
Error: Cannot find module 'ncp'

### ISSUE THREAD

**Issue by psabharwal123** [developit/preact-cli#718]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behaviour?**
Error: Cannot find module 'ncp'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (.....node_modules\preact-cli\lib\commands\create.js:5:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (....node_modules\preact-cli\lib\commands\index.js:2:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**If the current behaviour is a bug, please provide the steps to reproduce.**
build a preact cli template with 3.0.0-next.15

**What is the expected behaviour?**
i think ncp should moved to dependencies 

**If this is a feature request, what is motivation or use case for changing the behaviour?**
to build with preact-cli

**Please mention other relevant information.**
- Node version v8.11.3
- npm version 6.4.1
- Operating system windows
- CLI version 3.0.0-next.15
- Browser

**Comment by ForsakenHarmony** [comment]
Should be fixed in next 16
