### ISSUE TITLE
preact create widget not working

### ISSUE THREAD

**Issue by matthewharwood** [developit/preact-cli#758]
Try on @next and default CLI

```
$ preact create widget header
ℹ INFO Assuming you meant preactjs-templates/widget...
⠦ Installing dependencies✖ ERROR Error: Exited with status 1
    at closeArgsToError (/Users/matty/.nvm/versions/node/v10.15.3/lib/node_modules/preact-cli/node_modules/cross-spawn-promise/lib/index.js:20:16)
    at ChildProcess.<anonymous> (/Users/matty/.nvm/versions/node/v10.15.3/lib/node_modules/preact-cli/node_modules/cross-spawn-promise/lib/index.js:76:19)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
⠙ Installing dependencies
```
stalls here I cancel and go into widget

```
$ npm run dev
✖ ERROR ./node_modules/preact-cli/lib/lib/webpack/proxy-loader.js?{"cwd":"/Users/matty/Github/genesis/header","loader":"sass-loader","options":{"sourceMap":true}}!./src/components/hello-world/style.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/matty/Github/genesis/header/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/matty/Github/genesis/header/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.proxyLoader (/Users/matty/Github/genesis/header/node_modules/preact-cli/lib/lib/webpack/proxy-loader.js:20:12)
 @ ./src/components/hello-world/style.scss 4:14-226 18:2-22:4 19:20-232
```

**Do you want to request a *feature* or report a *bug*?**

**What is the current behaviour?**
Should run

- Node version 10.15.1
- npm version 6.4.1
- Operating system osx 10.14
- CLI version @latest
- Browser chrome

**Comment by matthewharwood** [comment]
Looks like this might be a dupe of https://github.com/developit/preact-cli/issues/657

**Comment by matthewharwood** [comment]
This was cleared up inside the slack.  Widget is to make a self contained component that can be used in other applications.
