### ISSUE TITLE
preact-cli@3.0.0-rc.1 fails to install in a fresh node container

### ISSUE THREAD

**Issue by dionjwa** [developit/preact-cli#802]
**Do you want to request a _feature_ or report a _bug_?**
_bug_

**What is the current behaviour?**
```
docker run --rm -ti node:8.16.0-alpine /bin/sh
# npm i --global preact-cli@3.0.0-rc.1
```
Shows:
```
npm WARN deprecated sw-precache@5.2.1: Please migrate to Workbox: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
npm WARN deprecated sw-toolbox@3.6.0: Please migrate to Workbox: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
/usr/local/bin/preact -> /usr/local/lib/node_modules/preact-cli/lib/index.js

> nodent-runtime@3.2.1 install /usr/local/lib/node_modules/preact-cli/node_modules/nodent-runtime
> node build.js

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/preact-cli/node_modules/nodent-runtime/dist/index.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/preact-cli/node_modules/nodent-runtime/build.js:5:4)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
npm WARN preact-cli@3.0.0-rc.1 requires a peer of preact@* but none is installed. You must install peer dependencies yourself.
npm WARN preact-cli@3.0.0-rc.1 requires a peer of preact-render-to-string@* but none is installed. You must install peer dependencies yourself.
npm WARN @preact/async-loader@3.0.0-rc.0 requires a peer of preact@^8.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-hot-loader@4.8.6 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-hot-loader@4.8.6 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/preact-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodent-runtime@3.2.1 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodent-runtime@3.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Other random npm packages install without errors, e.g. `webpack`.

**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**

Installing without any errors.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

- Node version: 8.16.0-alpine
- npm version: 8.16.0-alpine
- Operating system: alpine
- CLI version
- Browser

**Comment by ForsakenHarmony** [comment]
https://github.com/MatAtBread/nodent-runtime/issues/5

Not an issue with `preact-cli`

Also you shouldn't really do global installs in docker

**Comment by dionjwa** [comment]
Got it. But the last comment does not make sense. Global installs for project specific containers is absolutely a thing.

**Comment by ForsakenHarmony** [comment]
For a dev container maybe
